configure.yml: Check passing no flags with libuv installed
If libuv is installed on the system, then the libuv backend is automatically
enabled if no flags are passed. In that case we also require liblz4, and the
configure script fails if doesn't find it.

Signed-off-by: Free Ekanayaka <free@ekanayaka.io>

diff --git a/.github/workflows/configure.yml b/.github/workflows/configure.yml
--- a/.github/workflows/configure.yml
+++ b/.github/workflows/configure.yml
@@ -32,6 +32,12 @@ jobs:
       run: |
         sudo apt-get install -qq linux-libc-dev libuv1-dev
 
+    - name: Run ./configure
+      run: |
+        # Fail if no flags are passed, since libuv is installed but liblz4 is not.
+        ! ./configure 2>errors
+        tail -1 errors | grep -q "liblz4 required but not found" || (cat errors && false)
+
     - name: Install liblz4
       run: |
         sudo apt-get install -qq liblz4-dev
