configure.yml: Check passing --enable-uv with libuv not installed
Check that configure script fails in this case.

Signed-off-by: Free Ekanayaka <free@ekanayaka.io>

diff --git a/.github/workflows/configure.yml b/.github/workflows/configure.yml
--- a/.github/workflows/configure.yml
+++ b/.github/workflows/configure.yml
@@ -22,6 +22,12 @@ jobs:
       run: |
         autoreconf -i
 
+    - name: Run ./configure --enable-uv
+      run: |
+        # Fail if --enable-uv is passed, since libuv is not installed.
+        ! ./configure --enable-uv 2>errors
+        tail -1 errors | grep -q "libuv required but not found" || (cat errors && false)
+
     - name: Install libuv
       run: |
         sudo apt-get install -qq linux-libc-dev libuv1-dev
